# Generated by Django 5.2.11 on 2026-02-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavereasonpreset',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='leavetype',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameIndex(
            model_name='leaverequest',
            new_name='leave_leave_start_d_611c6f_idx',
            old_name='leave_leave_start_d5b5b7_idx',
        ),
        migrations.RenameIndex(
            model_name='leaverequest',
            new_name='leave_leave_employe_c033bc_idx',
            old_name='leave_leave_employee_1b3a56_idx',
        ),
        migrations.RemoveField(
            model_name='leavereasonpreset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='leavereasonpreset',
            name='label',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
