# Generated by Django 5.2.11 on 2026-02-04 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_rename_active_leavereasonpreset_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavereasonpreset',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='leavetype',
            old_name='is_active',
            new_name='active',
        ),
        migrations.AddField(
            model_name='leavereasonpreset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
