# Generated by Django 5.2.10 on 2026-02-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employeeprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='employee_photos/'),
        ),
    ]
