# Generated by Django 5.2.11 on 2026-02-12 13:27

import django.db.models.deletion
from django.db import migrations, models


def _backfill_user_organization(apps, schema_editor):
    Company = apps.get_model("organization", "Company")
    User = apps.get_model("users", "User")
    PasswordResetOTP = apps.get_model("users", "PasswordResetOTP")
    EmployeeRecord = apps.get_model("organization", "EmployeeRecord")

    default_company, _ = Company.objects.get_or_create(
        slug="default",
        defaults={"name": "Default Company", "active": True},
    )

    user_company_map: dict[int, int] = {}
    for row in EmployeeRecord.objects.exclude(user_id__isnull=True).values("user_id", "company_id"):
        if row["user_id"] and row["company_id"] and row["user_id"] not in user_company_map:
            user_company_map[row["user_id"]] = row["company_id"]

    for user in User.objects.filter(organization__isnull=True):
        user.organization_id = user_company_map.get(user.id, default_company.id)
        user.save(update_fields=["organization"])

    for otp in PasswordResetOTP.objects.filter(organization__isnull=True).select_related("user"):
        otp.organization_id = otp.user.organization_id or default_company.id
        otp.save(update_fields=["organization"])


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_company_uuid'),
        ('users', '0003_alter_employeeprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='password_otps', to='organization.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='organization.company'),
        ),
        migrations.RunPython(_backfill_user_organization, migrations.RunPython.noop),
    ]
