# Generated by Django 5.2.11 on 2026-02-13 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_admin_accounts(apps, schema_editor):
    User = apps.get_model("users", "User")
    AdminAccount = apps.get_model("users", "AdminAccount")

    for user in User.objects.filter(models.Q(is_superuser=True) | models.Q(is_staff=True)):
        AdminAccount.objects.get_or_create(
            user_id=user.id,
            defaults={
                "level": "PLATFORM",
                "organization_id": None,
                "can_manage_users": True,
                "can_manage_organizations": True,
            },
        )


def rollback_admin_accounts(apps, schema_editor):
    AdminAccount = apps.get_model("users", "AdminAccount")
    AdminAccount.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organizationdirectory_organizationtenant'),
        ('users', '0005_user_portal_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_portal_login',
        ),
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('PLATFORM', 'Platform Admin'), ('ORGANIZATION', 'Organization Admin')], default='ORGANIZATION', max_length=20)),
                ('can_manage_users', models.BooleanField(default=True)),
                ('can_manage_organizations', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_accounts', to='organization.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(seed_admin_accounts, rollback_admin_accounts),
    ]
