# Generated by Django 5.2.11 on 2026-02-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0004_organizationdirectory_organizationtenant"),
        ("users", "0006_remove_user_can_portal_login_adminaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this account.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="created_in_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization context used when this user was created.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="org_server_created_users",
                to="organization.company",
            ),
        ),
    ]
