# Generated by Django 5.2.11 on 2026-02-11 18:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=140)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='organization.company')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_cost_centers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company__name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING_JOIN', 'Pending Join'), ('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('EXITED', 'Exited')], default='PENDING_JOIN', max_length=20)),
                ('join_date', models.DateField(default=django.utils.timezone.localdate)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organization.company')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company__name', 'position__title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=120)),
                ('payload_json', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_events', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('rank_band', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_levels', to='organization.company')),
            ],
            options={
                'ordering': ['company__name', 'rank_band', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(blank=True, default='', max_length=80)),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='organization.company')),
            ],
            options={
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ManagerRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=220)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_changes', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_relationships', to='organization.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_relationships', to='organization.employeerecord')),
                ('manager_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_report_relationships', to='organization.employeerecord')),
            ],
            options={
                'ordering': ['-effective_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('unit_type', models.CharField(choices=[('DEPT', 'Department'), ('TEAM', 'Team')], default='TEAM', max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_units', to='organization.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organization.orgunit')),
            ],
            options={
                'ordering': ['company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrgAccessScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_scopes', to='organization.company')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_scopes', to='organization.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_access_scopes', to=settings.AUTH_USER_MODEL)),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_scopes', to='organization.orgunit')),
            ],
            options={
                'ordering': ['company__name', 'user_id'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('headcount', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='organization.company')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='organization.costcenter')),
                ('job_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='organization.joblevel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='organization.location')),
                ('manager_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_positions', to='organization.position')),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='organization.orgunit')),
            ],
            options={
                'ordering': ['company__name', 'title'],
            },
        ),
        migrations.AddField(
            model_name='employeerecord',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.position'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['company', 'active'], name='organizatio_company_a0920c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='costcenter',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['company', 'event_type', '-created_at'], name='organizatio_company_23b47a_idx'),
        ),
        migrations.AddIndex(
            model_name='joblevel',
            index=models.Index(fields=['company', 'rank_band'], name='organizatio_company_486e1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='joblevel',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['company', 'active'], name='organizatio_company_3af72c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='managerrelationship',
            index=models.Index(fields=['company', 'employee', 'effective_from'], name='organizatio_company_92178b_idx'),
        ),
        migrations.AddIndex(
            model_name='managerrelationship',
            index=models.Index(fields=['company', 'manager_employee', 'effective_from'], name='organizatio_company_b2c71b_idx'),
        ),
        migrations.AddIndex(
            model_name='orgunit',
            index=models.Index(fields=['company', 'unit_type'], name='organizatio_company_4c6062_idx'),
        ),
        migrations.AddIndex(
            model_name='orgunit',
            index=models.Index(fields=['company', 'active'], name='organizatio_company_f53d4d_idx'),
        ),
        migrations.AddIndex(
            model_name='orgunit',
            index=models.Index(fields=['parent'], name='organizatio_parent__f6cca1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orgunit',
            unique_together={('company', 'name', 'parent')},
        ),
        migrations.AddIndex(
            model_name='orgaccessscope',
            index=models.Index(fields=['company', 'user', 'active'], name='organizatio_company_7bf132_idx'),
        ),
        migrations.AddIndex(
            model_name='orgaccessscope',
            index=models.Index(fields=['org_unit', 'location'], name='organizatio_org_uni_d08497_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['company', 'org_unit'], name='organizatio_company_829993_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['company', 'location'], name='organizatio_company_c03eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['company', 'manager_position'], name='organizatio_company_17337f_idx'),
        ),
        migrations.AddIndex(
            model_name='employeerecord',
            index=models.Index(fields=['company', 'status'], name='organizatio_company_8447de_idx'),
        ),
        migrations.AddIndex(
            model_name='employeerecord',
            index=models.Index(fields=['company', 'position'], name='organizatio_company_94161a_idx'),
        ),
        migrations.AddIndex(
            model_name='employeerecord',
            index=models.Index(fields=['join_date'], name='organizatio_join_da_605c15_idx'),
        ),
    ]
