# Generated by Django 5.2.11 on 2026-02-11 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('TALENT', 'Talent Acquisition'), ('ONBOARDING', 'Onboarding')], max_length=20)),
                ('key', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=140)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('TEXTAREA', 'Textarea'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('EMAIL', 'Email'), ('PHONE', 'Phone'), ('URL', 'URL'), ('SELECT', 'Select'), ('CHECKBOX', 'Checkbox')], default='TEXT', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('placeholder', models.CharField(blank=True, default='', max_length=160)),
                ('help_text', models.CharField(blank=True, default='', max_length=220)),
                ('options', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='organization.company')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_fields', to='organization.location')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_fields', to='organization.orgunit')),
            ],
            options={
                'ordering': ['module', 'sort_order', 'label', 'id'],
                'indexes': [models.Index(fields=['company', 'module', 'active'], name='organizatio_company_ccc119_idx'), models.Index(fields=['company', 'org_unit', 'location'], name='organizatio_company_dd4cad_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'module', 'key', 'org_unit', 'location'), name='uniq_form_field_scope_key')],
            },
        ),
    ]
