# Generated by Django 5.2.11 on 2026-02-13 06:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_directory_and_tenants(apps, schema_editor):
    Company = apps.get_model("organization", "Company")
    OrganizationDirectory = apps.get_model("organization", "OrganizationDirectory")
    OrganizationTenant = apps.get_model("organization", "OrganizationTenant")

    for company in Company.objects.all().order_by("id"):
        directory, _ = OrganizationDirectory.objects.get_or_create(
            slug=company.slug,
            defaults={
                "name": company.name,
                "active": company.active,
                "company_id": company.id,
            },
        )
        updates = []
        if directory.company_id != company.id:
            directory.company_id = company.id
            updates.append("company")
        if directory.name != company.name:
            directory.name = company.name
            updates.append("name")
        if updates:
            directory.save(update_fields=updates)

        OrganizationTenant.objects.get_or_create(
            company_id=company.id,
            defaults={
                "directory_id": directory.id,
                "schema_name": company.slug,
                "domain": f"{company.slug}.local",
                "active": company.active,
            },
        )


def rollback_seed_directory_and_tenants(apps, schema_editor):
    OrganizationTenant = apps.get_model("organization", "OrganizationTenant")
    OrganizationDirectory = apps.get_model("organization", "OrganizationDirectory")
    OrganizationTenant.objects.all().delete()
    OrganizationDirectory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_company_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directory_entry', to='organization.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.SlugField(max_length=80, unique=True)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_config', to='organization.company')),
                ('directory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_config', to='organization.organizationdirectory')),
            ],
            options={
                'ordering': ['schema_name'],
            },
        ),
        migrations.RunPython(seed_directory_and_tenants, rollback_seed_directory_and_tenants),
    ]
