# Generated by Django 5.2.11 on 2026-02-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_allowedemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
