# Generated by Django 5.2.11 on 2026-02-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employeeprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='photo',
        ),
    ]
