# Generated by Django 5.2.11 on 2026-02-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_remove_employeeprofile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="role",
            field=models.CharField(
                choices=[("EMPLOYEE", "Employee"), ("HR", "HR"), ("ADMIN", "Admin")],
                default="EMPLOYEE",
                max_length=20,
            ),
        ),
    ]
