# Generated by Django 5.2.11 on 2026-02-16 20:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0004_organizationdirectory_organizationtenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AccessRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='IdpIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('SAML', 'SAML'), ('OIDC', 'OIDC')], max_length=32)),
                ('external_subject', models.CharField(max_length=255, unique=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idp_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-linked_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_host', models.CharField(max_length=255)),
                ('db_name', models.CharField(max_length=120)),
                ('db_user', models.CharField(max_length=120)),
                ('secret_ref', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, default='', max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_connection', to='organization.company')),
            ],
            options={
                'ordering': ['company__name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('LEAVE', 'Leave'), ('TALENT', 'Talent'), ('ONBOARDING', 'Onboarding')], max_length=24)),
                ('trigger_event', models.CharField(max_length=80)),
                ('conditions_json', models.JSONField(blank=True, default=dict)),
                ('actions_json', models.JSONField(blank=True, default=dict)),
                ('sla_minutes', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_rules', to='organization.company')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instances', to='organization.company')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='architecture.workflowrule')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('attempt_no', models.IntegerField(default=1)),
                ('last_error', models.TextField(blank=True, default='')),
                ('run_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='architecture.workflowinstance')),
            ],
            options={
                'ordering': ['-run_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_comments', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_comments', to='organization.company')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='architecture.workspacecomment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_mentions', to='organization.company')),
                ('mentioned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_mentions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkspacePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('AWAY', 'Away'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=16)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_presence', to='organization.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_presence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('LEAVE', 'Leave'), ('TALENT', 'Talent'), ('ONBOARDING', 'Onboarding'), ('GENERAL', 'General')], default='GENERAL', max_length=32)),
                ('title', models.CharField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_threads', to='organization.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_workspace_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='workspacecomment',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='architecture.workspacethread'),
        ),
        migrations.CreateModel(
            name='ImmutableAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=120)),
                ('entity_type', models.CharField(blank=True, default='', max_length=80)),
                ('entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('payload_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='immutable_audit_events', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immutable_audit_events', to='organization.company')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='architectur_company_ef5ca7_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobQueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=64)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('DEAD', 'Dead')], default='READY', max_length=16)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_queue_entries', to='organization.company')),
            ],
            options={
                'ordering': ['available_at', 'id'],
                'indexes': [models.Index(fields=['company', 'status', 'available_at'], name='architectur_company_2d9e80_idx')],
            },
        ),
        migrations.CreateModel(
            name='MfaFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_type', models.CharField(choices=[('TOTP', 'TOTP'), ('EMAIL_OTP', 'Email OTP'), ('SMS_OTP', 'SMS OTP'), ('WEBAUTHN', 'WebAuthn')], max_length=24)),
                ('factor_ref', models.CharField(blank=True, default='', max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_factors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'enabled'], name='architectur_user_id_66f9b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('INAPP', 'In App'), ('WEBHOOK', 'Webhook')], max_length=16)),
                ('template_code', models.CharField(max_length=80)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_outbox', to='organization.company')),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_outbox', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['company', 'status', '-created_at'], name='architectur_company_0ec53d_idx')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='architecture.accesspermission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='architecture.accessrole')),
            ],
            options={
                'ordering': ['role__code', 'permission__code'],
                'constraints': [models.UniqueConstraint(fields=('role', 'permission'), name='uniq_role_permission')],
            },
        ),
        migrations.CreateModel(
            name='SessionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_jti', models.CharField(max_length=64, unique=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=12)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_tokens', to='organization.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at', '-id'],
                'indexes': [models.Index(fields=['company', 'user', '-issued_at'], name='architectur_company_296caa_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantProvisionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('CREATE_DB', 'Create DB'), ('MIGRATE', 'Migrate'), ('BACKUP', 'Backup'), ('RESTORE', 'Restore')], max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_provision_jobs', to='organization.company')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['company', 'status', '-created_at'], name='architectur_company_5fb013_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantSchemaMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=80)),
                ('migration_name', models.CharField(max_length=255)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_migrations', to='organization.organizationtenant')),
            ],
            options={
                'ordering': ['-applied_at', '-id'],
                'indexes': [models.Index(fields=['tenant', '-applied_at'], name='architectur_tenant__8f88c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserRoleBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_bindings', to='organization.company')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bindings', to='architecture.accessrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_bindings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'role', 'company'), name='uniq_user_role_company_binding')],
            },
        ),
        migrations.AddIndex(
            model_name='workflowrule',
            index=models.Index(fields=['company', 'module', 'active'], name='architectur_company_549af2_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['company', 'status', '-started_at'], name='architectur_company_e9796d_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowsteprun',
            index=models.Index(fields=['instance', 'status', '-run_at'], name='architectur_instanc_910a64_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspacemention',
            constraint=models.UniqueConstraint(fields=('comment', 'mentioned_user'), name='uniq_workspace_mention_per_comment'),
        ),
        migrations.AddConstraint(
            model_name='workspacepresence',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='uniq_workspace_presence_per_user_company'),
        ),
        migrations.AddIndex(
            model_name='workspacethread',
            index=models.Index(fields=['company', 'module', '-created_at'], name='architectur_company_dcbdc6_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacecomment',
            index=models.Index(fields=['company', 'thread', 'created_at'], name='architectur_company_2607a8_idx'),
        ),
    ]
