# Generated by Django 5.2.11 on 2026-02-10 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_talentcandidate_onboardingtask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='talentcandidate',
            name='expected_join',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talentcandidate',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_talent_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='talentcandidate',
            name='resume_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='talentcandidate',
            index=models.Index(fields=['expected_join'], name='leaves_tale_expecte_74a147_idx'),
        ),
        migrations.AddIndex(
            model_name='talentcandidate',
            index=models.Index(fields=['owner', 'stage'], name='leaves_tale_owner_i_31b1b7_idx'),
        ),
    ]
