# Generated by Django 5.2.11 on 2026-02-11 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_talentcandidate_expected_join_talentcandidate_owner_and_more'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingtask',
            name='category',
            field=models.CharField(choices=[('HR', 'HR'), ('IT', 'IT'), ('FACILITIES', 'Facilities'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='onboardingtask',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_tasks', to='organization.company'),
        ),
        migrations.AddField(
            model_name='talentcandidate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talent_candidates', to='organization.company'),
        ),
        migrations.AddField(
            model_name='talentcandidate',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talent_candidates', to='organization.costcenter'),
        ),
        migrations.AddField(
            model_name='talentcandidate',
            name='hiring_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hiring_candidates', to='organization.employeerecord'),
        ),
        migrations.AddField(
            model_name='talentcandidate',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talent_candidates', to='organization.location'),
        ),
        migrations.AddField(
            model_name='talentcandidate',
            name='org_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talent_candidates', to='organization.orgunit'),
        ),
        migrations.AddIndex(
            model_name='onboardingtask',
            index=models.Index(fields=['company', 'status'], name='leaves_onbo_company_9d6538_idx'),
        ),
        migrations.AddIndex(
            model_name='talentcandidate',
            index=models.Index(fields=['company', 'stage'], name='leaves_tale_company_c1f7bf_idx'),
        ),
        migrations.AddIndex(
            model_name='talentcandidate',
            index=models.Index(fields=['org_unit', 'location'], name='leaves_tale_org_uni_9a116f_idx'),
        ),
    ]
