# Generated by Django 5.2.11 on 2026-02-11 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_onboardingtask_category_onboardingtask_company_and_more'),
        ('organization', '0002_organizationformfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingTaskCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_values', to='organization.organizationformfield')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='leaves.onboardingtask')),
            ],
            options={
                'ordering': ['field__sort_order', 'id'],
                'indexes': [models.Index(fields=['task', 'field'], name='leaves_onbo_task_id_bb1ded_idx'), models.Index(fields=['field'], name='leaves_onbo_field_i_b267a6_idx')],
                'unique_together': {('task', 'field')},
            },
        ),
        migrations.CreateModel(
            name='TalentCandidateCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='leaves.talentcandidate')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_values', to='organization.organizationformfield')),
            ],
            options={
                'ordering': ['field__sort_order', 'id'],
                'indexes': [models.Index(fields=['candidate', 'field'], name='leaves_tale_candida_b3379b_idx'), models.Index(fields=['field'], name='leaves_tale_field_i_afa151_idx')],
                'unique_together': {('candidate', 'field')},
            },
        ),
    ]
