# Generated by Django 5.2.11 on 2026-02-12 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _backfill_leave_organization(apps, schema_editor):
    Company = apps.get_model("organization", "Company")
    User = apps.get_model("users", "User")
    LeaveType = apps.get_model("leaves", "LeaveType")
    LeaveReasonPreset = apps.get_model("leaves", "LeaveReasonPreset")
    Holiday = apps.get_model("leaves", "Holiday")
    LeaveRequest = apps.get_model("leaves", "LeaveRequest")
    LeaveBalance = apps.get_model("leaves", "LeaveBalance")
    LeaveAttachment = apps.get_model("leaves", "LeaveAttachment")

    default_company, _ = Company.objects.get_or_create(
        slug="default",
        defaults={"name": "Default Company", "active": True},
    )

    for leave_type in LeaveType.objects.filter(organization__isnull=True):
        leave_type.organization_id = default_company.id
        leave_type.save(update_fields=["organization"])

    for reason in LeaveReasonPreset.objects.filter(organization__isnull=True):
        reason.organization_id = default_company.id
        reason.save(update_fields=["organization"])

    for holiday in Holiday.objects.filter(organization__isnull=True):
        holiday.organization_id = default_company.id
        holiday.save(update_fields=["organization"])

    user_org_map = {
        row["id"]: row["organization_id"]
        for row in User.objects.exclude(organization_id__isnull=True).values("id", "organization_id")
    }

    for leave_request in LeaveRequest.objects.filter(organization__isnull=True):
        leave_request.organization_id = user_org_map.get(leave_request.employee_id, default_company.id)
        leave_request.save(update_fields=["organization"])

    leave_type_org_map = {
        row["id"]: row["organization_id"]
        for row in LeaveType.objects.exclude(organization_id__isnull=True).values("id", "organization_id")
    }

    for balance in LeaveBalance.objects.filter(organization__isnull=True):
        balance.organization_id = (
            user_org_map.get(balance.user_id)
            or leave_type_org_map.get(balance.leave_type_id)
            or default_company.id
        )
        balance.save(update_fields=["organization"])

    leave_request_org_map = {
        row["id"]: row["organization_id"]
        for row in LeaveRequest.objects.exclude(organization_id__isnull=True).values("id", "organization_id")
    }

    for attachment in LeaveAttachment.objects.filter(organization__isnull=True):
        attachment.organization_id = leave_request_org_map.get(attachment.leave_request_id, default_company.id)
        attachment.save(update_fields=["organization"])


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0007_onboardingtaskcustomfieldvalue_and_more'),
        ('organization', '0003_company_uuid'),
        ('users', '0004_passwordresetotp_organization_user_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='holiday',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='organization.company'),
        ),
        migrations.AddField(
            model_name='leaveattachment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_attachments', to='organization.company'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='organization.company'),
        ),
        migrations.AddField(
            model_name='leavereasonpreset',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_reason_presets', to='organization.company'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='organization.company'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='organization.company'),
        ),
        migrations.RunPython(_backfill_leave_organization, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leavereasonpreset',
            name='label',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('organization', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('organization', 'user', 'leave_type', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='leavereasonpreset',
            unique_together={('organization', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='leavetype',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['organization', 'date'], name='leaves_holi_organiz_6194c7_idx'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['organization', 'user', 'year'], name='leaves_leav_organiz_54f610_idx'),
        ),
        migrations.AddIndex(
            model_name='leavereasonpreset',
            index=models.Index(fields=['organization', 'active'], name='leaves_leav_organiz_18ef78_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['organization', '-created_at'], name='leaves_leav_organiz_502a89_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['organization', 'status'], name='leaves_leav_organiz_752496_idx'),
        ),
        migrations.AddIndex(
            model_name='leavetype',
            index=models.Index(fields=['organization', 'active'], name='leaves_leav_organiz_ba7106_idx'),
        ),
    ]
