from __future__ import annotations

from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    AdminAccountListCreateAPIView,
    AdminUserDetailAPIView,
    AdminUserListCreateAPIView,
    AdminUserPasswordAPIView,
    AuditEventListAPIView,
    CalendarAPIView,
    CompanyDirectoryAPIView,
    CostCenterDirectoryAPIView,
    DashboardSummaryAPIView,
    HREmployeeDirectoryAPIView,
    HolidayDetailAPIView,
    HolidayImportICSAPIView,
    HolidayListCreateAPIView,
    JobLevelDirectoryAPIView,
    LeaveExportCSVAPIView,
    LeaveReasonPresetDetailAPIView,
    LeaveReasonPresetListAPIView,
    LeaveRequestDetailAPIView,
    LeaveRequestListCreateAPIView,
    LeaveReviewAPIView,
    LeaveTypeDetailAPIView,
    LeaveTypeListAPIView,
    LocationDirectoryAPIView,
    LoginAPIView,
    MeAPIView,
    MyIcalAPIView,
    OrganizationFormFieldDetailAPIView,
    OrganizationFormFieldListCreateAPIView,
    OrgUnitDirectoryAPIView,
    PositionDirectoryAPIView,
    PasswordResetRequestAPIView,
    PasswordResetVerifyAPIView,
    ProfileAPIView,
    ReportingChangeManagerAPIView,
    ReportingDirectReportsAPIView,
    ReportingTreeAPIView,
    TalentCandidateDetailAPIView,
    TalentCandidateListCreateAPIView,
    OnboardingTaskDetailAPIView,
    OnboardingTaskListCreateAPIView,
    OrganizationContextAPIView,
    OrganizationTenantListAPIView,
)

app_name = "api"

urlpatterns = [
    path("auth/login/", LoginAPIView.as_view(), name="login"),
    path("auth/password-reset/", PasswordResetRequestAPIView.as_view(), name="password_reset_request"),
    path("auth/password-reset/verify/<uuid:token>/", PasswordResetVerifyAPIView.as_view(), name="password_reset_verify"),
    path("auth/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("auth/me/", MeAPIView.as_view(), name="me"),
    path("dashboard/summary/", DashboardSummaryAPIView.as_view(), name="dashboard_summary"),
    path("profile/", ProfileAPIView.as_view(), name="profile"),
    path("leave/types/", LeaveTypeListAPIView.as_view(), name="leave_types"),
    path("leave/types/<int:pk>/", LeaveTypeDetailAPIView.as_view(), name="leave_type_detail"),
    path("leave/reasons/", LeaveReasonPresetListAPIView.as_view(), name="leave_reasons"),
    path("leave/reasons/<int:pk>/", LeaveReasonPresetDetailAPIView.as_view(), name="leave_reason_detail"),
    path("leave/requests/", LeaveRequestListCreateAPIView.as_view(), name="leave_requests"),
    path("leave/requests/<int:pk>/", LeaveRequestDetailAPIView.as_view(), name="leave_request_detail"),
    path("leave/requests/<int:pk>/review/", LeaveReviewAPIView.as_view(), name="leave_request_review"),
    path("leave/holidays/", HolidayListCreateAPIView.as_view(), name="holidays"),
    path("leave/holidays/<int:pk>/", HolidayDetailAPIView.as_view(), name="holiday_detail"),
    path("leave/holidays/import-ics/", HolidayImportICSAPIView.as_view(), name="holiday_import_ics"),
    path("leave/calendar/", CalendarAPIView.as_view(), name="calendar"),
    path("leave/export.csv", LeaveExportCSVAPIView.as_view(), name="export_csv"),
    path("leave/ical/", MyIcalAPIView.as_view(), name="my_ical"),
    path("org/context/", OrganizationContextAPIView.as_view(), name="org_context"),
    path("org/companies/", CompanyDirectoryAPIView.as_view(), name="org_companies"),
    path("org/tenants/", OrganizationTenantListAPIView.as_view(), name="org_tenants"),
    path("org/units/", OrgUnitDirectoryAPIView.as_view(), name="org_units"),
    path("org/form-fields/", OrganizationFormFieldListCreateAPIView.as_view(), name="org_form_fields"),
    path("org/form-fields/<int:pk>/", OrganizationFormFieldDetailAPIView.as_view(), name="org_form_field_detail"),
    path("org/locations/", LocationDirectoryAPIView.as_view(), name="org_locations"),
    path("org/cost-centers/", CostCenterDirectoryAPIView.as_view(), name="org_cost_centers"),
    path("org/job-levels/", JobLevelDirectoryAPIView.as_view(), name="org_job_levels"),
    path("org/positions/", PositionDirectoryAPIView.as_view(), name="org_positions"),
    path("hr/employees/", HREmployeeDirectoryAPIView.as_view(), name="hr_employees"),
    path("org/reporting/change-manager", ReportingChangeManagerAPIView.as_view(), name="reporting_change_manager"),
    path("org/reporting/direct-reports", ReportingDirectReportsAPIView.as_view(), name="reporting_direct_reports"),
    path("org/reporting/tree", ReportingTreeAPIView.as_view(), name="reporting_tree"),
    path("org/reporting/change-manager/", ReportingChangeManagerAPIView.as_view(), name="reporting_change_manager_slash"),
    path("org/reporting/direct-reports/", ReportingDirectReportsAPIView.as_view(), name="reporting_direct_reports_slash"),
    path("org/reporting/tree/", ReportingTreeAPIView.as_view(), name="reporting_tree_slash"),
    path("admin/users/", AdminUserListCreateAPIView.as_view(), name="admin_users"),
    path("admin/accounts/", AdminAccountListCreateAPIView.as_view(), name="admin_accounts"),
    path("admin/users/<int:pk>/", AdminUserDetailAPIView.as_view(), name="admin_user_detail"),
    path("admin/users/<int:pk>/password/", AdminUserPasswordAPIView.as_view(), name="admin_user_password"),
    path("talent/candidates/", TalentCandidateListCreateAPIView.as_view(), name="talent_candidates"),
    path("talent/candidates/<int:pk>/", TalentCandidateDetailAPIView.as_view(), name="talent_candidate_detail"),
    path("onboarding/tasks/", OnboardingTaskListCreateAPIView.as_view(), name="onboarding_tasks"),
    path("onboarding/tasks/<int:pk>/", OnboardingTaskDetailAPIView.as_view(), name="onboarding_task_detail"),
    path("audit/events/", AuditEventListAPIView.as_view(), name="audit_events"),
]
